name: "MBuild all samples"
description: "Build all samples"
runs:
  using: "composite"
  steps:

    - name: building sub-directories
      run: |
        echo '--------------------------------------------------------------------------'
        git clone https://github.com/approvals/ApprovalTests.cpp.git
        pushd develop_approvaltests_fetch_content
        ./build.sh
        popd

      shell: bash
