name: "MBuild all samples"
description: "Build all samples"
runs:
  using: "composite"
  steps:

    - name: building sub-directories
      run: |
        echo '--------------------------------------------------------------------------'
        pushd cmake_invoking_conan
        ./build.sh
        popd

        echo '--------------------------------------------------------------------------'
        pushd conan_cmake
        ./build.sh
        popd

        echo '--------------------------------------------------------------------------'
        pushd conan_cmake_find_package
        ./build.sh
        popd

        echo '--------------------------------------------------------------------------'
        pushd fetch_content_approvaltests_catch2
        ./build.sh
        popd

        echo '--------------------------------------------------------------------------'
        pushd fetch_content_approvaltests_catch2
        ./build.sh
        popd

# Disabled, as fails on Linux gcc builds.
# The ApprovalTests.cpp Boost_Tests run gives:
#   80/89 Test #80: Boost_Tests ..................................................................................***Failed    0.00 sec
#   Running 2 test cases...
#   *** No errors detected
#   Test setup error:
#        echo '--------------------------------------------------------------------------'
#        git clone https://github.com/approvals/ApprovalTests.cpp.git
#        pushd develop_approvaltests_fetch_content
#        ./build.sh
#        popd

      shell: bash
