name: "MBuild all samples"
description: "Build all samples"
runs:
  using: "composite"
  steps:

    - name: building sub-directories
      run: |
        echo '--------------------------------------------------------------------------'
        pushdir cmake_invoking_conan
        ./build.sh
        popdir

        echo '--------------------------------------------------------------------------'
        pushdir conan_cmake
        ./build.sh
        popdir

        echo '--------------------------------------------------------------------------'
        pushdir conan_cmake_find_package
        ./build.sh
        popdir

        echo '--------------------------------------------------------------------------'
        pushdir fetch_content_approvaltests_catch2
        ./build.sh
        popdir

        echo '--------------------------------------------------------------------------'
        pushdir fetch_content_approvaltests_catch2
        ./build.sh
        popdir

        echo '--------------------------------------------------------------------------'
        pushdir develop_approvaltests_fetch_content
        ./build.sh
        popdir

      shell: bash
